[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.build]
cmds = ["pip install --no-cache-dir -r requirements.txt"]

[start]
cmd = "uvicorn backend:app --host 0.0.0.0 --port 8000"
